# Generated by Django 4.0.4 on 2022-05-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=130)),
                ('time', models.DateTimeField(blank=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
