# Generated by Django 4.0.4 on 2022-06-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
